---
kind: pipeline
type: docker
name: publish-lua

trigger:
  ref:
    - refs/heads/master
  event:
    - push

steps:
  - name: lua5.1
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.1'
        - '5.1-alpine'
      dockerfile: lua/5.1/Dockerfile.alpine

  - name: lua5.2
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.2'
        - '5.2-alpine'
      dockerfile: lua/5.2/Dockerfile.alpine

  - name: lua5.3
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.3'
        - '5.3-alpine'
      dockerfile: lua/5.3/Dockerfile.alpine

  - name: lua5.4
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.4'
        - '5.4-alpine'
      dockerfile: lua/5.4/Dockerfile.alpine

  - name: lua5.1-ubuntu
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.1-ubuntu'
      dockerfile: lua/5.1/Dockerfile.ubuntu


  - name: lua5.2-ubuntu
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.2-ubuntu'
      dockerfile: lua/5.2/Dockerfile.ubuntu

  - name: lua5.3-ubuntu
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.3-ubuntu'
      dockerfile: lua/5.3/Dockerfile.ubuntu

  - name: lua5.4-ubuntu
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.4-ubuntu'
      dockerfile: lua/5.4/Dockerfile.ubuntu

---
kind: pipeline
type: docker
name: publish-luarocks

trigger:
  ref:
    - refs/heads/master
  event:
    - push

depends_on:
  - publish-lua

steps:
  - name: luarocks5.1
    image: plugins/docker
    settings:
      repo: imolein/luarocks
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.1'
      dockerfile: luarocks/5.1/Dockerfile

  - name: luarocks5.2
    image: plugins/docker
    settings:
      repo: imolein/luarocks
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.2'
      dockerfile: luarocks/5.2/Dockerfile

  - name: luarocks5.3
    image: plugins/docker
    settings:
      repo: imolein/luarocks
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.3'
      dockerfile: luarocks/5.3/Dockerfile

  - name: luarocks5.4
    image: plugins/docker
    settings:
      repo: imolein/luarocks
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.4'
      dockerfile: luarocks/5.4/Dockerfile

---
kind: pipeline
type: docker
name: monthly-rebuild-lua

trigger:
  ref:
    - refs/heads/master
  event:
    - cron
  cron:
    - monthly_build

steps:
  - name: lua5.1
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.1'
        - '5.1-alpine'
      dockerfile: lua/5.1/Dockerfile.alpine

  - name: lua5.2
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.2'
        - '5.2-alpine'
      dockerfile: lua/5.2/Dockerfile.alpine

  - name: lua5.3
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.3'
        - '5.3-alpine'
      dockerfile: lua/5.3/Dockerfile.alpine

  - name: lua5.4
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.4'
        - '5.4-alpine'
      dockerfile: lua/5.4/Dockerfile.alpine

  - name: lua5.1-ubuntu
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.1-ubuntu'
      dockerfile: lua/5.1/Dockerfile.ubuntu

  - name: lua5.2-ubuntu
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.2-ubuntu'
      dockerfile: lua/5.2/Dockerfile.ubuntu

  - name: lua5.3-ubuntu
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.3-ubuntu'
      dockerfile: lua/5.3/Dockerfile.ubuntu

  - name: lua5.4-ubuntu
    image: plugins/docker
    settings:
      repo: imolein/lua
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.4-ubuntu'
      dockerfile: lua/5.4/Dockerfile.ubuntu

---
kind: pipeline
type: docker
name: monthly-rebuild-luarocks

trigger:
  ref:
    - refs/heads/master
  event:
    - cron
  cron:
    - monthly_build

depends_on:
  - monthly-rebuild-lua

steps:
  - name: luarocks5.1
    image: plugins/docker
    settings:
      repo: imolein/luarocks
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.1'
      dockerfile: luarocks/5.1/Dockerfile

  - name: luarocks5.2
    image: plugins/docker
    settings:
      repo: imolein/luarocks
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.2'
      dockerfile: luarocks/5.2/Dockerfile

  - name: luarocks5.3
    image: plugins/docker
    settings:
      repo: imolein/luarocks
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.3'
      dockerfile: luarocks/5.3/Dockerfile

  - name: luarocks5.4
    image: plugins/docker
    settings:
      repo: imolein/luarocks
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      tags:
        - '5.4'
      dockerfile: luarocks/5.4/Dockerfile
