matrix:
  LUA_VERSION:
    - 5.1
    - 5.2
    - 5.3
    - 5.4
  FENNEL_VERSION:
    - 1.3.0

pipeline:
  lua-alpine:
    group: build-lua
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: lua/${LUA_VERSION}/Dockerfile.alpine
      dry_run: false
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      repo: imolein/lua
      tags:
        - ${LUA_VERSION}-alpine
        - ${LUA_VERSION}

  lua-ubuntu:
    group: build-lua
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: lua/${LUA_VERSION}/Dockerfile.ubuntu
      dry_run: false
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      repo: imolein/lua
      tags:
        - ${LUA_VERSION}-ubuntu

  luarocks-alpine:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: luarocks/${LUA_VERSION}/Dockerfile
      dry_run: false
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      repo: imolein/luarocks
      tags:
        - ${LUA_VERSION}-alpine
        - ${LUA_VERSION}

  fennel-alpine:
    group: build-fennel
    image: woodpeckerci/plugin-docker-buildx
    environment:
      - DOCKER_BUILDKIT=1
    settings:
      dockerfile: fennel/lua${LUA_VERSION}/Dockerfile.alpine
      dry_run: false
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      repo: imolein/fennel
      tags:
        - ${FENNEL_VERSION}-${LUA_VERSION}-alpine
        - ${FENNEL_VERSION}-${LUA_VERSION}

branches: master
