matrix:
  LUA_VERSION:
    - 5.1
    - 5.2
    - 5.3
    - 5.4
  FENNEL_VERSION:
    - 1.5.0

steps:
  - name: lua-alpine
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: lua/${LUA_VERSION}/Dockerfile.alpine
      dry_run: false
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      repo: imolein/lua
      tags:
        - ${LUA_VERSION}-alpine
        - ${LUA_VERSION}

  - name: lua-ubuntu
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: lua/${LUA_VERSION}/Dockerfile.ubuntu
      dry_run: false
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      repo: imolein/lua
      tags:
        - ${LUA_VERSION}-ubuntu

  - name: luarocks-alpine
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: luarocks/${LUA_VERSION}/Dockerfile.slim
      dry_run: false
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      repo: imolein/luarocks
      tags:
        - ${LUA_VERSION}-alpine-slim
        - ${LUA_VERSION}-slim
    depends_on:
      - lua-alpine

  - name: luarocks-alpine-fat
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: luarocks/${LUA_VERSION}/Dockerfile.fat
      dry_run: false
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      repo: imolein/luarocks
      tags:
        - ${LUA_VERSION}-alpine
        - ${LUA_VERSION}-fat
        - ${LUA_VERSION}
    depends_on:
      - lua-alpine

  - name: fennel-alpine
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: fennel/lua${LUA_VERSION}/Dockerfile.alpine
      dry_run: false
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
      repo: imolein/fennel
      tags:
        - ${FENNEL_VERSION}-${LUA_VERSION}-alpine
        - ${FENNEL_VERSION}-${LUA_VERSION}
    depends_on:
      - lua-alpine

when:
  branch: master
  event: [push, cron]
  cron: weekly rebuild
